import { Injectable, Logger } from '@nestjs/common';
import { hash } from 'argon2';
import { DatabaseService } from '../database/database.service';

@Injectable()
export class SeedService {
  private readonly logger = new Logger(SeedService.name);

  constructor(private readonly prisma: DatabaseService) {}

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  FULL RESET & SEED
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  async resetAndSeedAll() {
    this.logger.warn('🔄 Starting full database reset and seed...');

    await this.resetDatabase();

    // 1. Seed admin user
    const admin = await this.seedAdminUser();

    // 2. Seed additional staff users
    const users = await this.seedUsers(admin.id);

    // 3. Seed investors
    const investors = await this.seedInvestors();

    // 4. Seed purchase orders with items
    const purchaseOrders = await this.seedPurchaseOrders(admin.id, investors);

    // 5. Seed inventory from POs
    const inventoryItems = await this.seedInventory(purchaseOrders);

    // 6. Seed quotations
    const quotations = await this.seedQuotations(inventoryItems);

    // 7. Seed employees
    const employees = await this.seedEmployees(users);

    // 8. Seed expenses
    await this.seedExpenses(admin.id);

    this.logger.log('✅ Full database seed completed successfully');

    return {
      success: true,
      message: 'Database reset and seeded successfully',
      summary: {
        admin: { email: admin.email, password: 'admin123' },
        users: users.length + 1,
        investors: investors.length,
        purchaseOrders: purchaseOrders.length,
        inventoryItems: inventoryItems.length,
        quotations: quotations.length,
        employees: employees.length,
      },
    };
  }

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  EMPLOYEE-ONLY RESET & SEED (for salary testing)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  async resetAndSeedEmployees() {
    this.logger.warn('🔄 Starting employee tables reset and seed...');

    // Ensure at least one admin user exists
    let admin = await this.prisma.user.findFirst({ where: { role: 'ADMIN' } });
    if (!admin) {
      admin = await this.seedAdminUser();
    }

    // Clear employee-related tables in order (respecting FK constraints)
    await this.prisma.employeeAdvance.deleteMany({});
    await this.prisma.salary.deleteMany({});
    // Delete auto-generated expenses linked to employees
    await this.prisma.expense.deleteMany({
      where: {
        isAutoGenerated: true,
        category: { in: ['SALARY', 'EMPLOYEE_ADVANCE'] },
      },
    });
    await this.prisma.employee.deleteMany({});

    this.logger.log('Cleared employee tables');

    // Seed employees with salary-ready data
    const employees = await this.seedEmployeesForSalary(admin.id);

    // Seed some salary records (pending & paid)
    const salaries = await this.seedSalaryRecords(employees);

    // Seed some advance records
    const advances = await this.seedAdvanceRecords(employees, admin.id);

    this.logger.log('✅ Employee seed completed successfully');

    return {
      success: true,
      message: 'Employee tables reset and seeded successfully',
      summary: {
        adminEmail: admin.email,
        employees: employees.map((e) => ({
          id: e.id,
          employeeId: e.employeeId,
          name: e.name,
          baseSalary: e.baseSalary,
          advanceBalance: e.advanceBalance,
        })),
        salariesCreated: salaries.length,
        advancesCreated: advances.length,
      },
    };
  }

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  DATABASE RESET
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  private async resetDatabase() {
    this.logger.warn('Deleting all data from all tables...');

    // Delete in reverse dependency order
    await this.prisma.investorPayment.deleteMany({});
    await this.prisma.employeeAdvance.deleteMany({});
    await this.prisma.salary.deleteMany({});
    await this.prisma.employee.deleteMany({});
    await this.prisma.expense.deleteMany({});
    await this.prisma.retailSaleItem.deleteMany({});
    await this.prisma.retailSale.deleteMany({});
    await this.prisma.payment.deleteMany({});
    await this.prisma.billItem.deleteMany({});
    await this.prisma.bill.deleteMany({});
    await this.prisma.challanItem.deleteMany({});
    await this.prisma.challan.deleteMany({});
    await this.prisma.buyerPurchaseOrder.deleteMany({});
    await this.prisma.quotationItem.deleteMany({});
    await this.prisma.quotation.deleteMany({});
    await this.prisma.purchaseOrderPayment.deleteMany({});
    await this.prisma.purchaseOrderInvestment.deleteMany({});
    await this.prisma.inventory.deleteMany({});
    await this.prisma.purchaseOrderItem.deleteMany({});
    await this.prisma.purchaseOrder.deleteMany({});
    await this.prisma.investor.deleteMany({});
    await this.prisma.user.deleteMany({});

    this.logger.log('All tables cleared');
  }

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  SEED: ADMIN USER
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  private async seedAdminUser() {
    const hashedPassword = await hash('admin123');

    const admin = await this.prisma.user.create({
      data: {
        email: 'admin@middleman.com',
        name: 'Admin User',
        password: hashedPassword,
        role: 'ADMIN',
      },
    });

    this.logger.log(`Admin user created: ${admin.email}`);
    return admin;
  }

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  SEED: ADDITIONAL USERS
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  private async seedUsers(adminId: string) {
    const hashedPassword = await hash('password123');

    const usersData = [
      { email: 'manager@middleman.com', name: 'Manager User', role: 'MANAGER' as const },
      { email: 'staff1@middleman.com', name: 'Staff One', role: 'STAFF' as const },
      { email: 'staff2@middleman.com', name: 'Staff Two', role: 'STAFF' as const },
    ];

    const users = [];
    for (const userData of usersData) {
      const user = await this.prisma.user.create({
        data: { ...userData, password: hashedPassword },
      });
      users.push(user);
    }

    this.logger.log(`${users.length} additional users created`);
    return users;
  }

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  SEED: INVESTORS
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  private async seedInvestors() {
    const investorsData = [
      {
        name: 'Ahmed Rahman',
        email: 'ahmed.investor@example.com',
        phone: '+8801711111111',
        address: 'Dhaka, Bangladesh',
        bankAccount: '1234567890',
        bankName: 'Dutch Bangla Bank',
      },
      {
        name: 'Fatima Khan',
        email: 'fatima.investor@example.com',
        phone: '+8801722222222',
        address: 'Chittagong, Bangladesh',
        bankAccount: '0987654321',
        bankName: 'BRAC Bank',
      },
      {
        name: 'Karim Uddin',
        email: 'karim.investor@example.com',
        phone: '+8801733333333',
        address: 'Sylhet, Bangladesh',
        bankAccount: '1122334455',
        bankName: 'Islami Bank',
      },
    ];

    const investors = [];
    for (const data of investorsData) {
      const investor = await this.prisma.investor.create({ data });
      investors.push(investor);
    }

    this.logger.log(`${investors.length} investors created`);
    return investors;
  }

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  SEED: PURCHASE ORDERS
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  private async seedPurchaseOrders(adminId: string, investors: any[]) {
    const posData = [
      {
        poNumber: 'PO-00001',
        vendorName: 'China Electronics Co.',
        vendorCountry: 'China',
        vendorAddress: 'Shenzhen, Guangdong',
        vendorContact: 'Mr. Li Wei',
        vendorContactNo: '+8613800138000',
        paymentType: 'FULL' as const,
        status: 'RECEIVED' as const,
        totalAmount: 500000,
        taxAmount: 75000,
        dueAmount: 0,
        notes: 'Electronics import batch #1',
        createdBy: adminId,
        items: [
          { productName: 'Wireless Earbuds', description: 'Bluetooth 5.3 earbuds', quantity: 500, unitPrice: 400, taxPercentage: 15, totalPrice: 230000 },
          { productName: 'Smart Watch', description: 'Fitness tracker smartwatch', quantity: 200, unitPrice: 800, taxPercentage: 15, totalPrice: 184000 },
          { productName: 'Phone Case', description: 'Premium silicone phone case', quantity: 1000, unitPrice: 50, taxPercentage: 15, totalPrice: 57500 },
        ],
      },
      {
        poNumber: 'PO-00002',
        vendorName: 'India Textiles Ltd.',
        vendorCountry: 'India',
        vendorAddress: 'Mumbai, Maharashtra',
        vendorContact: 'Mr. Rajesh Sharma',
        vendorContactNo: '+919876543210',
        paymentType: 'DUE' as const,
        status: 'RECEIVED' as const,
        totalAmount: 300000,
        taxAmount: 45000,
        dueAmount: 150000,
        notes: 'Textile import batch #1',
        createdBy: adminId,
        items: [
          { productName: 'Cotton T-Shirt', description: '100% cotton casual t-shirt', quantity: 1000, unitPrice: 150, taxPercentage: 15, totalPrice: 172500 },
          { productName: 'Denim Jeans', description: 'Classic fit denim jeans', quantity: 300, unitPrice: 350, taxPercentage: 15, totalPrice: 120750 },
        ],
      },
    ];

    const purchaseOrders = [];

    for (const poData of posData) {
      const { items, ...poFields } = poData;

      const po = await this.prisma.purchaseOrder.create({
        data: {
          ...poFields,
          items: {
            create: items,
          },
        },
        include: { items: true },
      });

      // Create investment for first investor on first PO
      if (purchaseOrders.length === 0 && investors.length > 0) {
        await this.prisma.purchaseOrderInvestment.create({
          data: {
            purchaseOrderId: po.id,
            investorId: investors[0].id,
            investmentAmount: 300000,
            profitPercentage: 10,
            isFullInvestment: false,
          },
        });
      }

      purchaseOrders.push(po);
    }

    this.logger.log(`${purchaseOrders.length} purchase orders created`);
    return purchaseOrders;
  }

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  SEED: INVENTORY
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  private async seedInventory(purchaseOrders: any[]) {
    const inventoryItems = [];
    let codeCounter = 1;

    for (const po of purchaseOrders) {
      for (const item of po.items) {
        const inv = await this.prisma.inventory.create({
          data: {
            productCode: `PRD-${String(codeCounter).padStart(5, '0')}`,
            barcode: `BAR${String(codeCounter).padStart(8, '0')}`,
            productName: item.productName,
            description: item.description,
            quantity: item.quantity,
            purchasePrice: item.unitPrice,
            expectedSalePrice: item.unitPrice * 1.5,
            minStockLevel: 10,
            maxStockLevel: item.quantity * 2,
            purchaseOrderId: po.id,
          },
        });
        inventoryItems.push(inv);
        codeCounter++;
      }
    }

    this.logger.log(`${inventoryItems.length} inventory items created`);
    return inventoryItems;
  }

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  SEED: QUOTATIONS
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  private async seedQuotations(inventoryItems: any[]) {
    if (inventoryItems.length < 2) return [];

    const quotationsData = [
      {
        quotationNumber: 'QTN-00001',
        companyName: 'ABC Corporation',
        companyAddress: 'Gulshan, Dhaka',
        companyContact: '+8801911111111',
        subject: 'Electronics Supply Quotation',
        totalAmount: 150000,
        taxAmount: 22500,
        deliveryDays: 7,
        items: [
          {
            inventoryId: inventoryItems[0].id,
            quantity: 100,
            mrp: inventoryItems[0].expectedSalePrice * 1.2,
            unitPrice: inventoryItems[0].expectedSalePrice,
            packagePrice: inventoryItems[0].expectedSalePrice * 100,
            taxPercentage: 15,
            totalPrice: inventoryItems[0].expectedSalePrice * 100 * 1.15,
          },
        ],
      },
      {
        quotationNumber: 'QTN-00002',
        companyName: 'XYZ Trading House',
        companyAddress: 'Motijheel, Dhaka',
        companyContact: '+8801922222222',
        subject: 'Textile Supply Quotation',
        totalAmount: 200000,
        taxAmount: 30000,
        deliveryDays: 14,
        items: [
          {
            inventoryId: inventoryItems.length > 3 ? inventoryItems[3].id : inventoryItems[1].id,
            quantity: 200,
            mrp: 300,
            unitPrice: 250,
            packagePrice: 50000,
            taxPercentage: 15,
            totalPrice: 57500,
          },
        ],
      },
    ];

    const quotations = [];
    for (const qtData of quotationsData) {
      const { items, ...qtFields } = qtData;
      const qt = await this.prisma.quotation.create({
        data: {
          ...qtFields,
          items: { create: items },
        },
      });
      quotations.push(qt);
    }

    this.logger.log(`${quotations.length} quotations created`);
    return quotations;
  }

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  SEED: EMPLOYEES (full seed)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  private async seedEmployees(users: any[]) {
    const employeesData = [
      {
        employeeId: 'EMP-00001',
        name: 'Rahim Mia',
        email: 'rahim@middleman.com',
        phone: '+8801744444444',
        address: 'Mirpur, Dhaka',
        designation: 'Senior Developer',
        joinDate: new Date('2024-01-15'),
        baseSalary: 50000,
        homeRentAllowance: 15000,
        healthAllowance: 3000,
        travelAllowance: 5000,
        mobileAllowance: 1500,
        otherAllowances: 2000,
        overtimeRate: 500,
        userId: users.length > 0 ? users[0].id : undefined,
      },
      {
        employeeId: 'EMP-00002',
        name: 'Karim Sheikh',
        email: 'karim@middleman.com',
        phone: '+8801755555555',
        address: 'Dhanmondi, Dhaka',
        designation: 'Accountant',
        joinDate: new Date('2024-03-01'),
        baseSalary: 35000,
        homeRentAllowance: 10000,
        healthAllowance: 2500,
        travelAllowance: 3000,
        mobileAllowance: 1000,
        otherAllowances: 1500,
        overtimeRate: 350,
      },
      {
        employeeId: 'EMP-00003',
        name: 'Sadia Akhter',
        email: 'sadia@middleman.com',
        phone: '+8801766666666',
        address: 'Uttara, Dhaka',
        designation: 'Marketing Manager',
        joinDate: new Date('2024-06-10'),
        baseSalary: 45000,
        homeRentAllowance: 12000,
        healthAllowance: 3000,
        travelAllowance: 5000,
        mobileAllowance: 2000,
        otherAllowances: 3000,
        overtimeRate: 450,
      },
      {
        employeeId: 'EMP-00004',
        name: 'Nasir Hossain',
        email: 'nasir@middleman.com',
        phone: '+8801777777777',
        address: 'Banani, Dhaka',
        designation: 'Warehouse Supervisor',
        joinDate: new Date('2023-11-20'),
        baseSalary: 28000,
        homeRentAllowance: 8000,
        healthAllowance: 2000,
        travelAllowance: 3000,
        mobileAllowance: 1000,
        otherAllowances: 1000,
        overtimeRate: 280,
      },
      {
        employeeId: 'EMP-00005',
        name: 'Tamanna Sultana',
        email: 'tamanna@middleman.com',
        phone: '+8801788888888',
        address: 'Mohammadpur, Dhaka',
        designation: 'HR Executive',
        joinDate: new Date('2025-01-05'),
        baseSalary: 30000,
        homeRentAllowance: 9000,
        healthAllowance: 2500,
        travelAllowance: 3500,
        mobileAllowance: 1000,
        otherAllowances: 1500,
        overtimeRate: 300,
      },
    ];

    const employees = [];
    for (const data of employeesData) {
      const { userId, ...rest } = data;
      const employee = await this.prisma.employee.create({
        data: {
          ...rest,
          ...(userId ? { userId } : {}),
        },
      });
      employees.push(employee);
    }

    this.logger.log(`${employees.length} employees created`);
    return employees;
  }

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  SEED: EMPLOYEES FOR SALARY (employee-only endpoint)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  private async seedEmployeesForSalary(adminId: string) {
    const employeesData = [
      {
        employeeId: 'EMP-00001',
        name: 'Rahim Mia',
        email: 'rahim@middleman.com',
        phone: '+8801744444444',
        address: 'Mirpur, Dhaka',
        designation: 'Senior Developer',
        joinDate: new Date('2024-01-15'),
        baseSalary: 50000,
        homeRentAllowance: 15000,
        healthAllowance: 3000,
        travelAllowance: 5000,
        mobileAllowance: 1500,
        otherAllowances: 2000,
        overtimeRate: 500,
        advanceBalance: 5000, // Has existing advance
      },
      {
        employeeId: 'EMP-00002',
        name: 'Karim Sheikh',
        email: 'karim@middleman.com',
        phone: '+8801755555555',
        address: 'Dhanmondi, Dhaka',
        designation: 'Accountant',
        joinDate: new Date('2024-03-01'),
        baseSalary: 35000,
        homeRentAllowance: 10000,
        healthAllowance: 2500,
        travelAllowance: 3000,
        mobileAllowance: 1000,
        otherAllowances: 1500,
        overtimeRate: 350,
        advanceBalance: 0,
      },
      {
        employeeId: 'EMP-00003',
        name: 'Sadia Akhter',
        email: 'sadia@middleman.com',
        phone: '+8801766666666',
        address: 'Uttara, Dhaka',
        designation: 'Marketing Manager',
        joinDate: new Date('2024-06-10'),
        baseSalary: 45000,
        homeRentAllowance: 12000,
        healthAllowance: 3000,
        travelAllowance: 5000,
        mobileAllowance: 2000,
        otherAllowances: 3000,
        overtimeRate: 450,
        advanceBalance: 10000, // Larger advance balance
      },
      {
        employeeId: 'EMP-00004',
        name: 'Nasir Hossain',
        email: 'nasir@middleman.com',
        phone: '+8801777777777',
        address: 'Banani, Dhaka',
        designation: 'Warehouse Supervisor',
        joinDate: new Date('2023-11-20'),
        baseSalary: 28000,
        homeRentAllowance: 8000,
        healthAllowance: 2000,
        travelAllowance: 3000,
        mobileAllowance: 1000,
        otherAllowances: 1000,
        overtimeRate: 280,
        advanceBalance: 0,
      },
      {
        employeeId: 'EMP-00005',
        name: 'Tamanna Sultana',
        email: 'tamanna@middleman.com',
        phone: '+8801788888888',
        address: 'Mohammadpur, Dhaka',
        designation: 'HR Executive',
        joinDate: new Date('2025-01-05'),
        baseSalary: 30000,
        homeRentAllowance: 9000,
        healthAllowance: 2500,
        travelAllowance: 3500,
        mobileAllowance: 1000,
        otherAllowances: 1500,
        overtimeRate: 300,
        advanceBalance: 2000,
      },
    ];

    const employees = [];
    for (const data of employeesData) {
      const employee = await this.prisma.employee.create({ data });
      employees.push(employee);
    }

    this.logger.log(`${employees.length} employees created for salary testing`);
    return employees;
  }

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  SEED: SALARY RECORDS
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  private async seedSalaryRecords(employees: any[]) {
    const salaries = [];
    const currentDate = new Date();
    const currentMonth = currentDate.getMonth() + 1; // 1-12
    const currentYear = currentDate.getFullYear();

    // Previous month for paid salaries
    const prevMonth = currentMonth === 1 ? 12 : currentMonth - 1;
    const prevYear = currentMonth === 1 ? currentYear - 1 : currentYear;

    for (const emp of employees) {
      const allowances =
        emp.homeRentAllowance +
        emp.healthAllowance +
        emp.travelAllowance +
        emp.mobileAllowance +
        emp.otherAllowances;

      const grossSalary = emp.baseSalary + allowances;

      // Create a PAID salary for previous month
      const paidSalary = await this.prisma.salary.create({
        data: {
          employeeId: emp.id,
          month: prevMonth,
          year: prevYear,
          baseSalary: emp.baseSalary,
          allowances,
          overtimeHours: 5,
          overtimeAmount: (emp.overtimeRate || 0) * 5,
          bonus: 0,
          deductions: 0,
          advanceDeduction: 0,
          grossSalary,
          netSalary: grossSalary + (emp.overtimeRate || 0) * 5,
          status: 'PAID',
          paidDate: new Date(prevYear, prevMonth - 1, 28),
          paymentMethod: 'BANK_TRANSFER',
          reference: `SAL-${prevMonth}-${prevYear}-${emp.employeeId}`,
          notes: 'Seeded paid salary',
        },
      });
      salaries.push(paidSalary);

      // Create a PENDING salary for current month
      const pendingSalary = await this.prisma.salary.create({
        data: {
          employeeId: emp.id,
          month: currentMonth,
          year: currentYear,
          baseSalary: emp.baseSalary,
          allowances,
          overtimeHours: 0,
          overtimeAmount: 0,
          bonus: 0,
          deductions: 0,
          advanceDeduction: 0,
          grossSalary,
          netSalary: grossSalary,
          status: 'PENDING',
          notes: 'Seeded pending salary - ready to be paid',
        },
      });
      salaries.push(pendingSalary);
    }

    this.logger.log(`${salaries.length} salary records created`);
    return salaries;
  }

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  SEED: ADVANCE RECORDS
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  private async seedAdvanceRecords(employees: any[], adminId: string) {
    const advances = [];

    // Only create advance records for employees that have an advance balance
    for (const emp of employees) {
      if (emp.advanceBalance > 0) {
        const advance = await this.prisma.employeeAdvance.create({
          data: {
            employeeId: emp.id,
            amount: emp.advanceBalance,
            type: 'GIVEN',
            description: `Initial advance for ${emp.name}`,
            paymentMethod: 'CASH',
            balanceAfter: emp.advanceBalance,
          },
        });
        advances.push(advance);

        // Also create auto-generated expense for the advance
        await this.prisma.expense.create({
          data: {
            title: `Employee Advance - ${emp.name}`,
            description: `Advance payment to ${emp.name} (${emp.employeeId})`,
            amount: emp.advanceBalance,
            category: 'EMPLOYEE_ADVANCE',
            expenseDate: new Date(),
            paymentMethod: 'CASH',
            status: 'APPROVED',
            isAutoGenerated: true,
            employeeAdvanceId: advance.id,
            recordedBy: adminId,
          },
        });
      }
    }

    this.logger.log(`${advances.length} advance records created`);
    return advances;
  }

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  //  SEED: EXPENSES
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  private async seedExpenses(adminId: string) {
    const expensesData = [
      {
        title: 'Office Rent - January',
        description: 'Monthly office rent payment',
        amount: 25000,
        category: 'OFFICE_RENT' as const,
        paymentMethod: 'BANK_TRANSFER' as const,
        status: 'APPROVED' as const,
        recordedBy: adminId,
      },
      {
        title: 'Electricity Bill - January',
        description: 'Monthly electricity bill',
        amount: 5000,
        category: 'ELECTRICITY_BILL' as const,
        paymentMethod: 'BANK_TRANSFER' as const,
        status: 'APPROVED' as const,
        recordedBy: adminId,
      },
      {
        title: 'Internet & Phone',
        description: 'Monthly internet and phone bill',
        amount: 3500,
        category: 'INTERNET_PHONE_BILL' as const,
        paymentMethod: 'BANK_TRANSFER' as const,
        status: 'APPROVED' as const,
        recordedBy: adminId,
      },
      {
        title: 'Office Supplies',
        description: 'Stationery and printer supplies',
        amount: 2500,
        category: 'OFFICE_SUPPLIES_STATIONERY' as const,
        paymentMethod: 'CASH' as const,
        status: 'APPROVED' as const,
        recordedBy: adminId,
      },
      {
        title: 'Team Lunch',
        description: 'Monthly team refreshment',
        amount: 4000,
        category: 'REFRESHMENT_FOOD' as const,
        paymentMethod: 'CASH' as const,
        status: 'PENDING' as const,
        recordedBy: adminId,
      },
    ];

    for (const data of expensesData) {
      await this.prisma.expense.create({ data });
    }

    this.logger.log(`${expensesData.length} expenses created`);
  }
}
