export class CreateExpenseDto {
  title: string;
  description?: string;
  amount: number;
  category: ExpenseCategory;
  expenseDate: Date;
  paymentMethod: PaymentMethod;
  status: ExpenseStatus;
  notes?: string;
}

export enum ExpenseCategory {
  SALARY = 'SALARY',
  OFFICE_RENT = 'OFFICE_RENT',
  ELECTRICITY_BILL = 'ELECTRICITY_BILL',
  INTERNET_PHONE_BILL = 'INTERNET_PHONE_BILL',
  TRANSPORTATION_FUEL = 'TRANSPORTATION_FUEL',
  OFFICE_SUPPLIES_STATIONERY = 'OFFICE_SUPPLIES_STATIONERY',
  REPAIR_MAINTENANCE = 'REPAIR_MAINTENANCE',
  MARKETING_ADVERTISING = 'MARKETING_ADVERTISING',
  REFRESHMENT_FOOD = 'REFRESHMENT_FOOD',
  TRAINING_DEVELOPMENT = 'TRAINING_DEVELOPMENT',
  COURIER_DELIVERY = 'COURIER_DELIVERY',
  INVESTOR_PAYMENT = 'INVESTOR_PAYMENT',
  PURCHASE_ORDER_PAYMENT = 'PURCHASE_ORDER_PAYMENT',
  EMPLOYEE_ADVANCE = 'EMPLOYEE_ADVANCE',
  OTHER = 'OTHER',
}

export enum PaymentMethod {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CHEQUE = 'CHEQUE',
  CARD = 'CARD'
}

export enum ExpenseStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED'
}